services:
  - type: web
    name: viragem-tour-api
    env: node
    plan: free
    region: frankfurt
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3001
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: GOOGLE_CALENDAR_ID
        sync: false
      - key: VITE_MANAGER_PASSWORD
        sync: false
